### ISSUE TITLE
No conflict mode is not working with WordPress 4.5

### ISSUE THREAD

**Issue by tusharmaroo** [wp-premium/gravityforms#10]
@remcotolsma Can you have a look? It's messing up with Backbone. 
![issue-wordpress](https://cloud.githubusercontent.com/assets/662601/14796751/8f17248c-0b4c-11e6-9cad-f088a6df43c2.jpg)

**Comment by entr** [comment]
Better head to official support. This repo is only a mirror.

**Comment by tusharmaroo** [comment]
@entr Ahh.. didn't realized that! Doing that! But i can be of help to reproduce / debug the issue. Let me know if required. cc @remcotolsma

**Comment by remcotolsma** [comment]
Sorry, can't help with this, like @entr mentioned you can better contact Gravity Forms support for this.

> Gravity Forms, Git-ified. Synced manual! This repository is just a mirror of the Gravity Forms plugin. Please do not send pull requests and issues.
