### ISSUE TITLE
Export csv : filename is not correctly encoded under windows in French

### ISSUE THREAD

**Issue by LittleSnake42** [wp-premium/gravityforms#14]
**Hi there,**
we have issues with filenames when exporting entries from a form with french accents in the title (*e.g.* a form called *"Si vous ne souhaitez pas b**é**n**é**ficier de ce service"* will be exported with title *"si-vous-ne-souhaitez-pas-b%c3%a9%c3%a9ficier-de-ce-service-DATE"*) 

![image](https://cloud.githubusercontent.com/assets/24939197/21773994/4c6262bc-d691-11e6-806c-75c665439f0a.png)

A related topic with a possible solution : http://stackoverflow.com/questions/1525830/how-do-i-use-filesystem-functions-in-php-using-utf-8-strings

Would be great to fix it, seems really quick

**Comment by remcotolsma** [comment]
> This repository is just a mirror of the Gravity Forms plugin. **Please do not send pull requests and issues.**

https://github.com/wp-premium/gravityforms
